//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("ConnectivityInfo", Namespace="MusicShareSvc", IsNullable=false)]
public partial class ConnectivityInfoType {
    
    private string[] loginField;
    
    private IpEndPointInfo[] ipV4EndPointsField;
    
    private IpEndPointInfo[] ipV6EndPointsField;
    
    private string bluetoothAddressField;
    
    private string deviceNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Login")]
    public string[] Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IpV4EndPoints")]
    public IpEndPointInfo[] IpV4EndPoints {
        get {
            return this.ipV4EndPointsField;
        }
        set {
            this.ipV4EndPointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IpV6EndPoints")]
    public IpEndPointInfo[] IpV6EndPoints {
        get {
            return this.ipV6EndPointsField;
        }
        set {
            this.ipV6EndPointsField = value;
        }
    }
    
    /// <remarks/>
    public string BluetoothAddress {
        get {
            return this.bluetoothAddressField;
        }
        set {
            this.bluetoothAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeviceName {
        get {
            return this.deviceNameField;
        }
        set {
            this.deviceNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
public partial class IpEndPointInfo {
    
    private string addressField;
    
    private int portField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("Ok", Namespace="MusicShareSvc", IsNullable=false)]
public partial class OkType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("RegisterSpec", Namespace="MusicShareSvc", IsNullable=false)]
public partial class RegisterSpecType {
    
    private string loginField;
    
    private string passwordField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("RequestActivationSpec", Namespace="MusicShareSvc", IsNullable=false)]
public partial class RequestActivationSpecType {
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("ChangePasswordSpec", Namespace="MusicShareSvc", IsNullable=false)]
public partial class ChangePasswordSpecType {
    
    private string newPasswordField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NewPassword {
        get {
            return this.newPasswordField;
        }
        set {
            this.newPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("ChangeEmailSpec", Namespace="MusicShareSvc", IsNullable=false)]
public partial class ChangeEmailSpecType {
    
    private string passwordField;
    
    private string oldEmailField;
    
    private string newEmailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OldEmail {
        get {
            return this.oldEmailField;
        }
        set {
            this.oldEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NewEmail {
        get {
            return this.newEmailField;
        }
        set {
            this.newEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("ResetPasswordSpec", Namespace="MusicShareSvc", IsNullable=false)]
public partial class ResetPasswordSpecType {
    
    private string loginField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("LoginSpec", Namespace="MusicShareSvc", IsNullable=false)]
public partial class LoginSpecType {
    
    private string loginField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("ProfileFootprintInfo", Namespace="MusicShareSvc", IsNullable=false)]
public partial class ProfileFootprintInfoType {
    
    private string loginField;
    
    private string emailFootprintField;
    
    private bool isActivatedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EmailFootprint {
        get {
            return this.emailFootprintField;
        }
        set {
            this.emailFootprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsActivated {
        get {
            return this.isActivatedField;
        }
        set {
            this.isActivatedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("Stamp", Namespace="MusicShareSvc", IsNullable=false)]
public partial class StampInfoType {
    
    private long valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedErrorInfoType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("ErrorInfo", Namespace="MusicShareSvc", IsNullable=false)]
public partial class ErrorInfoType {
    
    private string messageField;
    
    private string stackTraceField;
    
    private ErrorInfoType innerErrorField;
    
    private string typeNameField;
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public string StackTrace {
        get {
            return this.stackTraceField;
        }
        set {
            this.stackTraceField = value;
        }
    }
    
    /// <remarks/>
    public ErrorInfoType InnerError {
        get {
            return this.innerErrorField;
        }
        set {
            this.innerErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TypeName {
        get {
            return this.typeNameField;
        }
        set {
            this.typeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MusicShareSvc")]
[System.Xml.Serialization.XmlRootAttribute("ExtendedErrorInfo", Namespace="MusicShareSvc", IsNullable=false)]
public partial class ExtendedErrorInfoType : ErrorInfoType {
    
    private string rawErrorInfoField;
    
    /// <remarks/>
    public string RawErrorInfo {
        get {
            return this.rawErrorInfoField;
        }
        set {
            this.rawErrorInfoField = value;
        }
    }
}
